# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       .travis.yml for gcc-5 compiler support on Travis CI , https://gist.github.com/cotsog/3ce84675af0d74438d91
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages


language: shell

env:
  - CONDA_PYTHON=3.6
  - CONDA_PYTHON=3.7
  - CONDA_PYTHON=3.7.1
  - CONDA_PYTHON=3.7.3
  - CONDA_PYTHON=nightly

os:
  - linux
  - osx

before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history $HOME/miniconda/envs/test-environment/conda-meta/history $HOME/miniconda/lib/python3.6/__pycache__ $HOME/miniconda/lib/python3.7/__pycache__;
  - touch $HOME/miniconda/conda-meta/history;

before_install:
  # When C++14 support becomes more clear, consider revision
  # https://docs.travis-ci.com/user/multi-os/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
    fi

install:
  # When C++14 support becomes more clear, consider revision
  # https://docs.travis-ci.com/user/multi-os/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -qq g++-6;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
    fi
  # Obtain miniconda installer for the OS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  # Install miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  # Add miniconda path
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Forget all rememberd locations
  - hash -r
  # Conda setup options
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # To help debugging
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  # Useful for debugging any issues with conda
  - conda info -a
  # Apply python module recipies
  - if [[ "$TOXENV" == "3.6" ]]; then
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.3.6.yml;
    elif [[ "$TOXENV" == "3.7" ]]; then
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.3.7.yml;
    else
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.nightly.yml;
    fi
  - source activate test-environment
  - conda list

# https://lord.io/blog/2014/travis-multiple-subdirs/
script: py.test 
notifications:
    email:
        - kangwon.lee.edu@gmail.com
