# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       .travis.yml for gcc-5 compiler support on Travis CI , https://gist.github.com/cotsog/3ce84675af0d74438d91
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages

matrix:
  include:
    - os : linux
      sudo: required
      language: python
      python: "3.6"
    - os : linux
      sudo: required
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7
    - os : linux
      language: python
      python: "nightly"
    - os : osx
      sudo: required
      language: generic
    - os : osx
      sudo: required
      python: "nightly"


before_install:
  # C++14
  # https://docs.travis-ci.com/user/multi-os/
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -qq g++-6;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f ./tests/environment.3.6.yml;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f ./tests/environment.3.7.yml;
    else
      conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f ./tests/environment.nightly.yml;
    fi
  - source activate test-environment
  - conda list

# https://lord.io/blog/2014/travis-multiple-subdirs/
script: cd tests && py.test
notifications:
    email:
        - kangwon.lee.edu@gmail.com
