# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python>=3.6
- numpy>=1.12.1
- scipy>=0.19
- sympy>=1.1.1
- jupyter>=1.0.0
- pytest>=3.2.1
- matplotlib>=2.0.2
