name: CI (OSX)

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]
        anaconda: [2019.07]

        bashrc: [.bash_profile]

    steps:
    - uses: actions/checkout@v1
    - uses: kangwonlee/setup-conda@fda0d4d
        with: 
          yml: ./tests/environment.${{ matrix.anaconda }}.yml
    - name: test_ipynb
      env:
        WORKFLOWS_OS: ${{ matrix.os }}
        HOME: ..
        SHELL: ${{ matrix.shell }}
        BASHRC: ${{ matrix.bashrc }}
        CONDA_PYTHON: ${{ matrix.anaconda }}
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/create_env_test_osx.sh
